<section id="dropdown-onwards-writing-1" class="question dropdown dropdown-click closed col-12 col-lg-10 col-xl-8 mb-4">
    <a href="#" class="dropdown-header">
        <span>1. Read an article about children. Then answer the questions.</span>
        <button class="dropdown-button text-right">
            <i class="dropdown-icon fas fa-chevron-down"></i>
        </button>
    </a>
    <main class="dropdown-menu-content one-question-container px-xl-4">
        <h3 class="title col-12 mb-4 h5"><b>Why do Children Love to be Scared?</b> <i>by Ed Allen</i></h3>
        <img src="" alt="">
        <div class="info mx-auto my-4">
            <p>One day I took my 6-year-old daughter to an amusement park. They had all the usual rides: rollercoasters and so on, but they also had a Haunted House, you know, the kind you move through a building in a slow-moving car and see scary things like ghosts that appear out of the dark, things that brush across your face, that kind of thing. I have to admit it was quite scary – at one point a face covered in blood appeared right in front of us and even my heart missed a beat. All the time my daughter was saying “Daddy I’m scared, when will it end?” but of course we had no choice but to complete the ride. When it finally came to an end and we left, she was very pale and quiet, as if she’d had a truly horrendous experience, although within five minutes she was eating an ice-cream and begging to go on the rollercoaster.</p>
            <p>The funny thing is when we got home my wife asked her "How was your day? What was the best part?"</p>
            <p>"The Haunted House!", she replied!</p>
            <p>Intrigued, I did some research on how a child can have a frightening experience but then realise later that they actually enjoyed it. It seems that kids love to be scared, and this is why:</p>
            <p>As children grow, they realise that they have negative emotions. At varying times they can feel sad, angry, lonely or scared. They also realise that they have to learn to control these emotions. They understand that, when they feel sad for example, they have to do something about it. So they watch something funny on TV, or call a friend who they know will make them feel better. But fear is something else. One of the reasons we feel fear is that we know bad things are going to happen but we have no control over it. We also don’t know what the result will be or how we are going to be affected.</p>
            <p>What better then, than a Haunted House, or a scary film or book? Deep inside, a child knows that the house experience will come to an end, and everything will be normal again. It’s the same with a film or book. Both have endings, and neither will actually have a negative effect on their life. When the end finally comes, the child feels exhilarated that they survived the experience. They controlled their fear emotion and that is a victory for the child.</p>
            <p>All well and good, but of course things can go too far which is why many films and experiences are age-restricted. If fear generated by a film encourages a child to feel that there is genuine danger that they hadn’t previously known about, that is something they won’t recover from. I heard about a child who saw the film ‘Jaws’ (about a man-eating shark) when she was only three and subsequently had a lifelong fear of going into the sea because she was scared she’d be eaten by a shark</p>
        </div>

        <div class="a complete col-12 col-lg-10 col-xl-8 mx-auto my-4 position-relative">
            <label for="identeado" class="indent">a. In your own words, describe the child’s experience.</label>
            <textarea id="identeado" name="B1_Onwards:RW1[1]" class="px-2 text"></textarea>
        </div>
        <div class="b complete col-12 col-lg-10 col-xl-8 mx-auto my-4 position-relative">
            <label for="identeado-two" class="indent">b.. In your own words, answer the question "Why do Children Love to be Scared?</label>
            <textarea id="identeado-two" name="B1_Onwards:RW1[2]" class="px-2 text"></textarea>
        </div>
    </main>
</section>